edges-collab/edges-cal

- src/edges_cal/cal_coefficients.py
raise an error if the input frequency range is larger than the LNA S11 can support.
> error if frequency range is wrong

- src/edges_cal/cal_coefficients.py
- src/edges_cal/xrfi.py
This PR adds the ability to specify all possible options for all sources individually in `CalibrationObservation`. It opens up the possibility of sending, eg. `n_terms` to the `SwitchCorrection` constructor for each source.
> Add ability to specify individual source options

- README.md
- examples/settings.yaml
- src/edges_cal/cal_coefficients.py
- src/edges_cal/cli.py
- src/edges_cal/xrfi.py
Adds a function to do a term sweep over a number of terms. 
Still, there's the possibility of adding iterations over run_num/repeat_num here, which is not yet implemented. Also, the RMS is taken over the calibration sources (hot/ambient/short/long), and ignores any possible antenna simulators. Not sure if this is the right way to do things. 
We can add those separately in another PR if they seem useful.
I know @gitul has done a bit of this before, so would be happy to have his comments.
> Term sweep

- src/edges_cal/xrfi.py
- tests/test_xrfi.py
This normalises the _output_ of `xrfi_watershed`.
> fix: watershed xrfi needs to return info dict

- src/edges_cal/modelling.py
- src/edges_cal/xrfi.py
This suppresses the ill-conditioned matrix warning when solving the matrix equation in `modelling.py`. I'm still not absolutely convinced that's a good idea (perhaps we should rather be _fixing_ it), but most things I find seem to say it should be fine (and we're getting reasonable results for now).
> Suppress rcond warning

- src/edges_cal/modelling.py
Fixes a small bug where parameters passed to __call__() from `Foreground` weren't passed through.
> fix: pass parameters through from Foreground

- src/edges_cal/cal_coefficients.py
- tests/test_cal_coeff.py
This makes it possible to pass in a different manual directory for the switch correction in a `Calibration` object(eg. if the calfile is downloaded to a different computer, the link to the switch correction will not work). 
It might be worthwhile -- in the future -- just saving the switch correction data into the calfile itself.
> fix: don't check for internal switch goodness

- .vscode/settings.json
- src/edges_cal/tools.py
- tests/test_freq.py
This makes the frequencies in the lab calibration actually match those that are measured and stored in .acq files.
> fix: frequencies for edges spectrometer were slightly off

- .gitignore
- CHANGELOG.md
- src/edges_cal/cal_coefficients.py
- src/edges_cal/modelling.py
- src/edges_cal/receiver_calibration_func.py
- src/edges_cal/reflection_coefficient.py
- src/edges_cal/s11_correction.py
- src/edges_cal/tools.py
- src/edges_cal/types.py
- src/edges_cal/xrfi.py
- tests/test_cal_coeff.py
- tests/test_modelling.py
It now consists of smaller, self-consistent
classes that are based on `attrs` and are read-only (but clonable). There is an
explicit split between a `Model` and a `FixedLinearModel` which is defined at some
coordinates `x`, allowing the latter to provide speedups for fitting lots of data at
the same coordinates. They are also YAML-read/writable.
BREAKING CHANGE: Calls to Model need to be updated to not provide default_x.
This can be provided by doing `Model().at(x=array)`.
> feat: updated modelling API

- src/edges_cal/modelling.py
Restores the `f_center` kw to Foreground Models (including LinLog) for backwards compat of reading saved YAML files etc.
> fix: restore f_center kw for fg models

- src/edges_cal/cal_coefficients.py
Adds the ability to set the internal_switch resistance value when creating a `CalibrationObservation` (previously it was hard set by the `definition.yaml`).
> feat: ability to set the internal_switch resistance

- src/edges_cal/cal_coefficients.py
- tests/test_cal_coeff.py
Simple fix for the `inject()` method for new attrs-based classes.
> fix: inject() method to use new attrs capabilities

- setup.cfg
- src/edges_cal/cal_coefficients.py
- tests/test_spec.py
This adds the `temperature_range` parameter to `LoadSpectrum` which allows one to cut on the temperatures used. This also necessitated being able to cross match timestamps from the spectra and thermistor measurements, which could come in handy for other things in the future.
> feat: ability to specify a temperature range in LoadSpectrum

- src/edges_cal/spectra.py
Instead of caching based on the whole observation definition, just cache based on the spectra and resistance (since that's all that's needed for a `LoadSpectrum`).
> perf: tighter hash for spectra so less re-reads

- src/edges_cal/simulate.py
This fixes a small issue with simulating q_ant from a calibration observation. It turns out you should multiply by the beam correction instead of dividing (when simulating), at least, if it's defined as in the bayesian calibration paper (and edges_estimate)
> fix: multiply by bm_corr instead of divide

- .github/labels.yml
- .github/workflows/labeler.yml
- setup.cfg
- src/edges_cal/xrfi.py
This adds `xrfi_model_nonlinear_window` which in tests gets MUCH better agreement in flagging RFI with Alan's code. The only remaining discrepancy is in the model fits themselves, which are only accurate to the kelvin-level at first, and sub-kelvin at higher iterations.
> feat: add xrfi_model_nonlinear_window

- src/edges_cal/reflection_coefficient.py
Fixes the `SMatrix` class to not use slots.
> fix: smatrix class no slots

- src/edges_cal/calobs.py
Adds the ability to write `Calibrator` objects from the object themselves, which makes much more sense.
> refactor: ability to write Calibrator objects from the object itself

- src/edges_cal/calobs.py
- tests/test_calobs.py
**Summary**
Fixes an issue with reading old v0 calfiles, which are written by hickle. It is not a perfect fix, as I can't figure out how to read the name of the model and transform classes, but it is a reasonable patch for the few cases we might need it.
**Checklist:** 
**Meta-info:**
> fix: v0 calfile reader for hickle files

- pyproject.toml
- tests/test_temp.py
- tests/test_xrfi.py
Fixes tests running, see https://github.com/smarie/python-pytest-cases/issues/364
> deps: pin pytest to <8.4.0 for now
